model = "parts/mini_engine/mini_engine.fbx"

name = "Mini Tube Mk. 1"
country = "United States"
manufacturer = "Rocket Factory"
description = "Generates a bit of thrust"


[p_root]
	mass = 100.0


[[machine]]
	id = "main_engine"
	script = "core:machines/engine.lua"
	thrust = 10.0
	nozzle = "m_nozzle"
