[renderer]
	width = 1366
	height = 768
	scale = 0.75
	type = "windowed"	# "windowed", "fullscreen" or "windowed fullscreen"

[renderer.quality]
	sun_shadow_size = 1024
	sun_terrain_shadow_size = 1024
	secondary_shadow_size = 512
	env_map_size = 256
